name: thunderstore_client CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.14.0
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: crystal tool format --check
  specs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.14.0
    steps:
    - uses: actions/checkout@v4
    - name: Set up Crystal cache
      uses: actions/cache@v4
      id: crystal-cache
      with:
        path: |
          ~/.cache/crystal
          lib
          lucky_tasks
        key: ${{ runner.os }}-crystal-${{ hashFiles('**/shard.lock') }}
        restore-keys: |
          ${{ runner.os }}-crystal-
    - name: Install shards
      if: steps.crystal-cache.outputs.cache-hit != 'true'
      run: shards check || shards install --ignore-crystal-version
    - name: Run tests
      run: crystal spec
