name: Crystal CI

on:
  push:
    branches: [ "docs" ]
  pull_request:
    branches: [ "docs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Generate docs
      run: crystal docs
